#!/bin/sh
. /etc/profile
set -eu
JAVA=${JAVA_HOME:-/usr}/bin/java
JAVA_OPTS=${JAVA_OPTS--XX:+UseSerialGC -XX:GCTimeRatio=10}

exec "$JAVA" \
  $JAVA_OPTS \
  -Djava.awt.headless=true \
  -Dlogback.configurationFile=/opt/housing/logback.xml \
  -jar /opt/housing/housing.jar \
  >> /var/log/housing/housing.log 2>&1
